framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%&queue_name=async'
        retry_strategy:
          max_retries: 0

      failed: '%env(MESSENGER_TRANSPORT_DSN)%&queue_name=failed'

    routing:
      'App\Provider\Gitlab\Async\IncomingGitlabEventMessage': async
      'App\Provider\Sentry\Async\IncomingSentryEventMessage': async
