twig:
  default_path: '%kernel.project_dir%/templates'
  globals:
    sentry_dsn: ~ # This disables sentry by default, we enable it explicitly in the prod environment
    sentry_release: '%sentry_release%'
