stages:
  - prepare
  - lint
  - build
  - tests
  - sentry
  - deploy

include:
  # Prepare
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/symfony/install-dependencies.yml'
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/yarn/install-js-dependencies.yml'

  # Lint
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/shell/shellcheck.yml'
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/php/phan.yml'
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/ts/tslint.yml'
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/yaml/yamllint.yml'
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/sass/sasslint.yml'
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/vue/vuelint.yml'

  # Build
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/yarn/build-prod.yml'

  # Tests
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/php/phpunit.yml'
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/symfony/check-security.yml'

  # Sentry
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/sentry/sentry.yml'

  # Deploy
  - project: 'intern/runner-templates'
    ref: "2.4"
    file: '/deploy/deploy.yml'

sentry-release-staging:
  only:
    # Effectively disable the job, directly deploy production
    - external

sentry-release-production:
  script:
    - sentry-cli releases new -p ${SENTRY_PROJECT} ${SENTRY_PROJECT}@${CI_COMMIT_SHA:0:8}
    - sentry-cli releases set-commits --commit "intern / ${SENTRY_PROJECT}@${CI_COMMIT_SHA}" ${SENTRY_PROJECT}@${CI_COMMIT_SHA:0:8}
    - sentry-cli releases finalize ${SENTRY_PROJECT}@${CI_COMMIT_SHA:0:8}
    - sentry-cli releases deploys ${SENTRY_PROJECT}@${CI_COMMIT_SHA:0:8} new --env prod
  only:
    - master
  except:
    - schedules

deploy-staging:
  only:
    # Effectively disable the job, directly deploy production
    - external

deploy-production:
  only:
    - master
  except:
    - schedules

deploy-docker:
  stage: deploy
  image: docker:latest
  interruptible: true
  needs:
    - job: install-dependencies
      artifacts: true
    - job: build-assets
      artifacts: true
  cache:
    key:
      files:
        - composer.lock
      prefix: ${CI_PROJECT_PATH_SLUG}_composer
    paths:
      - vendor/
    policy: pull
  before_script:
    - docker pull docker:latest
  script:
    - export VERSION=${CI_COMMIT_TAG:-latest}
    - echo "Building drenso/argus:$VERSION"
    - docker build -t drenso/argus:$VERSION -f docker/argus/Dockerfile .
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push drenso/argus:$VERSION
  tags:
    - docker-build
  only:
    - master
    - tags
  except:
    - schedules
