stages:
  - prepare
  - lint
  - build
  - tests
  - sentry
  - deploy

include:
  # Prepare
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/symfony/install-dependencies.yml'
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/yarn/install-js-dependencies.yml'

  # Lint
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/shell/shellcheck.yml'
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/php/phan.yml'
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/ts/tslint.yml'
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/yaml/yamllint.yml'
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/sass/sasslint.yml'
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/vue/vuelint.yml'

  # Build
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/yarn/build-prod.yml'

  # Tests
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/php/phpunit.yml'
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/symfony/check-security.yml'

  # Sentry
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/sentry/sentry.yml'

  # Deploy
  - project: 'intern/runner-templates'
    ref: "2.2"
    file: '/deploy/deploy.yml'
