controllers:
  resource: ../../src/Controller/
  type: annotation

gitlab_provider:
  resource: ../../src/Provider/Gitlab/Controller
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation
